### ISSUE TITLE
What's the mean of 'uncertainty'? 

### ISSUE THREAD

**Issue by liguopeng0923** [tudelft-iv/CrossViewMetricLocalization#2]
As mentioned, I dont know the mean of 'uncertainty' , which appears many times in your paper.

**Comment by ZiminXia** [comment]
Hi Guopeng,

Given a pair of input images, our model outputs a discrete probabilistic distribution.
The distribution identifies not only the predicted location but also the model's confidence in its predictions. The uncertainty of the prediction is quantified by this distribution. 
A sharper distribution corresponds to lower uncertainty, which means the model has higher confidence. Similarly, a more uniform distribution means higher uncertainty. In this case, the model might find multiple aerial locations that match well with the ground image and thus have low confidence.

Hope this helps the understanding.

Best regards,
Zimin

**Comment by liguopeng0923** [comment]
Thanks for your good interpretation. I have no problems.
